var products = [
    { id: 1, name: 'Saveur cafée', description: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur reprehenderit ipsum accusamus dolor tenetur molestiae labore temporibus? Omnis, id eligendi. Porro corrupti quasi, tenetur excepturi ratione itaque maiores officiis commodi?", price: 15.00, image: 'img/savon1.jpg', qty: 1 },
    { id: 2, name: 'Joie du Noël', description: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur reprehenderit ipsum accusamus dolor tenetur molestiae labore temporibus? Omnis, id eligendi. Porro corrupti quasi, tenetur excepturi ratione itaque maiores officiis commodi?", price: 19.00, image: 'img/savon2.jpg', qty: 1 },
    { id: 3, name: 'Douceur du Miel', description: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur reprehenderit ipsum accusamus dolor tenetur molestiae labore temporibus? Omnis, id eligendi. Porro corrupti quasi, tenetur excepturi ratione itaque maiores officiis commodi?", price: 10.00, image: 'img/savon3.jpg', qty: 1 },
    { id: 4, name: 'Lavende magique', description: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur reprehenderit ipsum accusamus dolor tenetur molestiae labore temporibus? Omnis, id eligendi. Porro corrupti quasi, tenetur excepturi ratione itaque maiores officiis commodi?", price: 15.00, image: 'img/savon4.jpg', qty: 1 },
    { id: 5, name: 'Gateau rose', description: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur reprehenderit ipsum accusamus dolor tenetur molestiae labore temporibus? Omnis, id eligendi. Porro corrupti quasi, tenetur excepturi ratione itaque maiores officiis commodi?", price: 7.00, image: 'img/savon5.jpg', qty: 1 },
    { id: 6, name: 'Nuit étoilée', description: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur reprehenderit ipsum accusamus dolor tenetur molestiae labore temporibus? Omnis, id eligendi. Porro corrupti quasi, tenetur excepturi ratione itaque maiores officiis commodi?", price: 15.00, image: 'img/savon6.jpg', qty: 1 },
    { id: 7, name: 'Vin chaud', description: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur reprehenderit ipsum accusamus dolor tenetur molestiae labore temporibus? Omnis, id eligendi. Porro corrupti quasi, tenetur excepturi ratione itaque maiores officiis commodi?", price: 7.00, image: 'img/savon7.jpg', qty: 1 },
    { id: 8, name: 'Coeur de pirate', description: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur reprehenderit ipsum accusamus dolor tenetur molestiae labore temporibus? Omnis, id eligendi. Porro corrupti quasi, tenetur excepturi ratione itaque maiores officiis commodi?", price: 20.00, image: 'img/savon8.jpg', qty: 1 },
    { id: 9, name: 'Belle avanture', description: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur reprehenderit ipsum accusamus dolor tenetur molestiae labore temporibus? Omnis, id eligendi. Porro corrupti quasi, tenetur excepturi ratione itaque maiores officiis commodi?", price: 10.00, image: 'img/savon9.jpg', qty: 1 }
]